feat: 회원가입 + 로그인 구현
RhythmPalette/RhythmPalette-Server pull request #21
Opened 2024-02-02 11:32 UTC by HyunwooYi

### 📌 PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 🔗 반영 브랜치
feature/login -> dev

### ✨ 변경 사항
User 도메인 
- 비회원, 회원, 관리자 역할 추가

회원가입 구현 
- (1) 아이디 중복 확인 기능
- (2) 비밀번호 일치 여부 확인 기능
- (3) 유저 이메일로 인증 번호 전송 기능
- (4) 유저가 입력한 인증 번호와 서버에 인증 번호 비교 기능
- (5) (1) ~(4)의 정보를 합하여 회원 가입 완료

로그인 구현
- 시큐리티 (회원가입/로그인) 적용

### ✅ 테스트 결과
- [x] 로그인 아이디 중복
- [x] 비밀번호 조건 확인
- [x] 이메일 인증번호 전송
- [x] 이메일 인증번호 일치 확인
- [x] 유저 회원가입
- [x] 유저 로그인시 token 생성
- [x] 유저는 token을 통해 api 접속

2024-02-02 15:05 UTC, chaeyeon0130 requested changes
수고하셨습니다!

2024-02-02 15:05 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/PaletteApplication.java
> +
엇 이것들은 무엇을 의미하는 코드일까요? 특별히 CommandLineRunner를 이용해서 구현하신 이유가 있을까요??

2024-02-02 15:05 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
> +        }
엇 저희 예외 처리 try/catch 말고 CustomExceptionHandler에서 전역적으로 해주기로 하지 않았나요??

2024-02-02 15:23 UTC, HyunwooYi commented on src/main/java/com/umc/Palette/PaletteApplication.java
> +
서버 실행할 때마다 Admin 계정이 없으면 만드는 코드였는데 지우는 걸 깜빡했네요 수정할게요!

2024-02-02 15:37 UTC, HyunwooYi commented on src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
> +        }
앗 그러면 이런 식으로 작성을 하는건가요?
```
RestController
@RequiredArgsConstructor
@RequestMapping("/posts")
public class PostController {

    private final PostService postService;

    @PostMapping
    public BaseResponse<PostResponseDTO> addPost(@RequestBody PostRequestDTO.AddDTO addDTO/*, HttpServletRequest request*/){
        postService.addPost(addDTO/*,request*/);
        return BaseResponse.<PostResponseDTO>builder()
                .code(200)
                .isSuccess(true)
                .message("게시글이 작성되었습니다.")
                .build();
    }
}
```

그러면 아래 코드와 같이BaseResponseStatus는 작성하지 않고 위 코드처럼 바로바로 사용할 값만 작성해주면 될까요?
```
public enum BaseResponseStatus {

    // -------- 성공 코드 시작 -------- //
    SUCCESS(true, 1000, "요청에 성공했습니다."),
    NOT_EXISTS_LOGIN_ID(true, 2000, "해당 아이디를 사용할 수 있습니다."),
    SATISFIED_PW_CRITERIA(true, 2001, "비밀번호가 확인되었습니다."),
...
}


```

2024-02-03 09:14 UTC, rlJzr approved these changes
고생하셨습니다! 앞으론 유저부분도 추가해서 구현할게요!

2024-02-04 02:28 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
> +        }
> 앗 그러면 이런 식으로 작성을 하는건가요?

네 맞습니다!

> 그러면 아래 코드와 같이BaseResponseStatus는 작성하지 않고 위 코드처럼 바로바로 사용할 값만 작성해주면 될까요?

BaseResponseStatus에 따로 작성하고 싶으면, 작성한 후 해당 내용을 사용하면 되지 않을까요..?

2024-02-04 03:20 UTC, 7dngur7 approved these changes
수고하셨습니다!

2024-02-04 14:35 UTC, merged