feat: 이미지 생성 기능 구현
RhythmPalette/RhythmPalette-Server pull request #40
Opened 2024-02-11 01:08 UTC by rlJzr

### 📌 PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 🔗 반영 브랜치
feature/image -> dev

### ✨ 변경 사항
이미지 생성 및 저장 기능 구현

### ✅ 테스트 결과

2024-02-11 06:09 UTC, chaeyeon0130 requested changes
수고하셨습니다!

2024-02-11 06:09 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/domain/post/service/ImageService.java
> +        String kakaoApiKey = "90e550050f17eef60e69216d9fc2d4b9";
api key 이렇게 public하게 공개되어도 괜찮을까요,,

2024-02-11 06:09 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/domain/post/dto/PostRequestDTO.java
> +        private Integer samples;
prompt랑 samples는 각각 어떠한 값을 의미하는 걸까요??!

2024-02-11 06:09 UTC, chaeyeon0130 commented on src/main/java/com/umc/Palette/domain/post/domain/Image.java
> +    private Long seed;
이 seed 필드의 의미도 궁금해요!!

2024-02-12 00:50 UTC, rlJzr commented on src/main/java/com/umc/Palette/domain/post/service/ImageService.java
> +        String kakaoApiKey = "90e550050f17eef60e69216d9fc2d4b9";
헉 깃허브에는 제외하고 올린다는걸 실수했네요 ㅜ

2024-02-12 00:52 UTC, rlJzr commented on src/main/java/com/umc/Palette/domain/post/dto/PostRequestDTO.java
> +        private Integer samples;
prompt는 이미지를 생성할 제시어이고 samples은 생성할 이미지의 개수입니다!
https://developers.kakao.com/docs/latest/ko/karlo/rest-api
관련 링크 남겨놓겠습니다.

2024-02-12 00:55 UTC, rlJzr commented on src/main/java/com/umc/Palette/domain/post/domain/Image.java
> +    private Long seed;
이미지를 생성할 때 사용된 시드값으로 같은 주제의 이미지를 재생성할 때 사용합니다.
우리 서비스에선 재생성기능이 없는걸로 알고있지만 Karlo API 문서에서 이미지의 필수 필드값이라고 명시되어있는것으로 이해하여 추가해놓았습니다.
https://developers.kakao.com/docs/latest/ko/karlo/rest-api

2024-02-13 01:39 UTC, HyunwooYi approved these changes
수고하셨습니다 👍

2024-02-13 01:39 UTC, merged